/* GENERATED by sidekick.py — do not hand-edit. 2026-07-20T19:23:26Z | 1 events, 0 open */
window.SIDEKICK = {
  "events": [
    {
      "task": "Desc smoke",
      "category": "chore",
      "completed_at": "2026-07-20T19:23:26Z",
      "sat_for_hours": 0,
      "orchestrator": null,
      "via": "phone",
      "from": "dalton"
    }
  ],
  "active": [],
  "stats": {
    "total": 1,
    "by_category": {
      "chore": 1
    },
    "median_sat_hours": 0,
    "by_weekday": [
      1,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "by_hour": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      1,
      0,
      0,
      0,
      0
    ],
    "streak_days": 1
  },
  "lists": []
};
