/* GENERATED by sidekick.py — do not hand-edit. 2026-07-20T21:10:41Z | 0 events, 5 open */
window.SIDEKICK = {
  "events": [],
  "active": [
    {
      "id": "20260720-build-a-hot-weather-shortlist-with-costs-hours-and",
      "task": "Build a hot-weather shortlist with costs hours and backup notes",
      "category": "chore",
      "sat_for_hours": 1,
      "plan": null,
      "from": "sidekick",
      "shared": true,
      "parent": "20260720-research-things-to-do-in-or-near-harpenden-london-",
      "list": null,
      "status": "open",
      "description": null
    },
    {
      "id": "20260720-find-heat-safe-indoor-activities-near-harpenden-fo",
      "task": "Find heat-safe indoor activities near Harpenden for young kids",
      "category": "chore",
      "sat_for_hours": 1,
      "plan": null,
      "from": "sidekick",
      "shared": true,
      "parent": "20260720-research-things-to-do-in-or-near-harpenden-london-",
      "list": null,
      "status": "open",
      "description": null
    },
    {
      "id": "20260720-identify-shaded-parks-splash-pads-and-pools-near-h",
      "task": "Identify shaded parks splash pads and pools near Harpenden",
      "category": "chore",
      "sat_for_hours": 1,
      "plan": {
        "summary": "Shortlist close shade first, then pick the water option by travel appetite: Harpenden indoor pool, Verulamium splash park, Cassiobury splash pools, or Hitchin Lido.",
        "steps": [
          {
            "text": "For lowest-effort hot-day shade, go to Rothamsted Park: play area, benches, nature trails, mature oaks, woodland pockets and lime avenue, with Harpenden Leisure Centre next door if swimming becomes the better option.",
            "href": "https://www.harpenden.gov.uk/green-spaces/rothamsted-park"
          },
          {
            "text": "For a cooler picnic/play walk without swimming, use Batford Springs Local Nature Reserve: wet woodland, riverside path, boardwalk, picnic benches and play park; do not swim in the water.",
            "href": "https://www.harpenden.gov.uk/green-spaces/batford-springs-nature-reserve"
          },
          {
            "text": "For closest indoor swimming, check Harpenden Leisure Centre on Leyton Road: 25m main pool plus learner/teaching pool; call 01582 767722 if timetable booking is unclear.",
            "href": "https://www.swimming.org/poolfinder/pools/25814/Harpenden/Harpenden+Leisure+Centre/"
          },
          {
            "text": "For the closest splash-park outing, check/book Verulamium Splash Park in St Albans, then use Verulamium Park's 175 acres as the shaded/park part of the trip.",
            "href": "https://www.everyoneactive.com/centre/verulamium-splash-park/"
          },
          {
            "text": "For the best free water-play facilities if travelling farther, pick Cassiobury Park: free paddling pools, two splash pools, splash pads, water jets/fountains, changing, toilets and cafe kiosk.",
            "href": "https://www.watford.gov.uk/cassiobury-park-3/cassiobury-park-activities/3"
          },
          {
            "text": "For a proper outdoor-pool day, choose Hitchin Lido in season: 50m heated outdoor pool open May–September, with indoor 25m pool, toddler pool and Splash Café as backups.",
            "href": "https://visithitchin.com/attractions/hitchin-lido/"
          }
        ]
      },
      "from": "sidekick",
      "shared": true,
      "parent": "20260720-research-things-to-do-in-or-near-harpenden-london-",
      "list": null,
      "status": "open",
      "description": null
    },
    {
      "id": "20260720-research-car-free-routes-from-harpenden-to-cooling",
      "task": "Research car-free routes from Harpenden to cooling day trips",
      "category": "chore",
      "sat_for_hours": 1,
      "plan": {
        "summary": "Prioritise walkable Harpenden cooling options first; use St Albans as the easiest rail splash trip, with Watford and Hitchin only after live journey checks.",
        "steps": [
          {
            "text": "Default to Rothamsted Park plus Harpenden Leisure Centre: walk/cycle from central Harpenden, use the park for shade/play and the leisure centre for an indoor swim if the heat peaks.",
            "href": "https://www.swimming.org/poolfinder/pools/25814/Harpenden/Harpenden+Leisure+Centre/"
          },
          {
            "text": "Use Batford Springs as the nearby shaded nature option; pack for picnic/play only and do not swim in the water.",
            "href": "https://www.harpenden.gov.uk/green-spaces/batford-springs-nature-reserve"
          },
          {
            "text": "For the best simple car-free splash day, take Thameslink/National Rail from Harpenden to St Albans City, then walk 25–35 minutes or take a local bus/taxi to Verulamium Splash Park / Verulamium Park.",
            "href": "https://www.stalbans.gov.uk/verulamium-park"
          },
          {
            "text": "For bigger free water play, live-plan Cassiobury Park: either Harpenden → St Albans City → St Albans Abbey → Watford Junction, or a London/TfL route to Watford Underground for the shorter final walk.",
            "href": "https://www.watford.gov.uk/cassiobury-park-3/cassiobury-park-activities/3"
          },
          {
            "text": "Treat Hitchin Lido as a bonus outdoor-pool day only if live train planning looks acceptable; the lido is good, but the Harpenden car-free route is comparatively awkward.",
            "href": "https://visithitchin.com/attractions/hitchin-lido/"
          }
        ]
      },
      "from": "sidekick",
      "shared": true,
      "parent": "20260720-research-things-to-do-in-or-near-harpenden-london-",
      "list": null,
      "status": "open",
      "description": null
    },
    {
      "id": "20260720-research-things-to-do-in-or-near-harpenden-london-",
      "task": "Research things to do in or near Harpenden, London if heat strikes while we are there",
      "category": "chore",
      "sat_for_hours": 1,
      "plan": {
        "summary": "Broken into 4 sub-tasks",
        "steps": [
          {
            "text": "Find heat-safe indoor activities near Harpenden for young kids — [[20260720-find-heat-safe-indoor-activities-near-harpenden-fo]]"
          },
          {
            "text": "Research car-free routes from Harpenden to cooling day trips — [[20260720-research-car-free-routes-from-harpenden-to-cooling]]"
          },
          {
            "text": "Identify shaded parks splash pads and pools near Harpenden — [[20260720-identify-shaded-parks-splash-pads-and-pools-near-h]]"
          },
          {
            "text": "Build a hot-weather shortlist with costs hours and backup notes — [[20260720-build-a-hot-weather-shortlist-with-costs-hours-and]]"
          }
        ]
      },
      "from": "dalton",
      "shared": true,
      "parent": null,
      "list": "england-vacation",
      "status": "open",
      "description": "We are two families, with two kids each, kids are 3, 5 and 7. One family does not have a car."
    }
  ],
  "stats": {
    "total": 0,
    "by_category": {},
    "median_sat_hours": null,
    "by_weekday": [
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "by_hour": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "streak_days": 0
  },
  "lists": [
    {
      "id": "england-vacation",
      "name": "England - Vacation",
      "created": "2026-07-20T20:37:47Z"
    }
  ]
};
