/* GENERATED by sidekick.py — do not hand-edit. 2026-07-20T20:39:50Z | 0 events, 1 open */
window.SIDEKICK = {
  "events": [],
  "active": [
    {
      "id": "20260720-research-things-to-do-in-or-near-harpenden-london-",
      "task": "Research things to do in or near Harpenden, London if heat strikes while we are there",
      "category": "chore",
      "sat_for_hours": 0,
      "plan": null,
      "from": "dalton",
      "shared": true,
      "parent": null,
      "list": "england-vacation",
      "status": "open",
      "description": "We are two families, with two kids each, kids are 3, 5 and 7. One family does not have a car."
    }
  ],
  "stats": {
    "total": 0,
    "by_category": {},
    "median_sat_hours": null,
    "by_weekday": [
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "by_hour": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "streak_days": 0
  },
  "lists": [
    {
      "id": "england-vacation",
      "name": "England - Vacation",
      "created": "2026-07-20T20:37:47Z"
    }
  ]
};
