/* GENERATED by sidekick.py — do not hand-edit. 2026-07-19T13:50:33Z | 0 events, 1 open */
window.SIDEKICK = {
  "events": [],
  "active": [
    {
      "id": "20260719-test",
      "task": "Test",
      "category": "chore",
      "sat_for_hours": 3,
      "plan": null,
      "from": "wife",
      "shared": true,
      "parent": null,
      "list": null,
      "status": "open"
    }
  ],
  "stats": {
    "total": 0,
    "by_category": {},
    "median_sat_hours": null,
    "by_weekday": [
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "by_hour": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "streak_days": 0
  },
  "lists": []
};
