/* GENERATED by sidekick.py — do not hand-edit. 2026-07-20T19:24:01Z | 0 events, 0 open */
window.SIDEKICK = {
  "events": [],
  "active": [],
  "stats": {
    "total": 0,
    "by_category": {},
    "median_sat_hours": null,
    "by_weekday": [
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "by_hour": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "streak_days": 0
  },
  "lists": []
};
