/* GENERATED by sidekick.py — do not hand-edit. 2026-07-20T20:59:34Z | 1 events, 5 open */
window.SIDEKICK = {
  "events": [
    {
      "task": "Build a hot-weather shortlist with costs hours and backup notes",
      "category": "chore",
      "completed_at": "2026-07-20T20:59:34.582Z",
      "sat_for_hours": 0,
      "orchestrator": null,
      "via": "phone",
      "from": "sidekick"
    }
  ],
  "active": [
    {
      "id": "20260720-find-heat-safe-indoor-activities-near-harpenden-fo",
      "task": "Find heat-safe indoor activities near Harpenden for young kids",
      "category": "chore",
      "sat_for_hours": 0,
      "plan": null,
      "from": "sidekick",
      "shared": true,
      "parent": "20260720-research-things-to-do-in-or-near-harpenden-london-",
      "list": null,
      "status": "open",
      "description": null
    },
    {
      "id": "20260720-identify-shaded-parks-splash-pads-and-pools-near-h",
      "task": "Identify shaded parks splash pads and pools near Harpenden",
      "category": "chore",
      "sat_for_hours": 0,
      "plan": null,
      "from": "sidekick",
      "shared": true,
      "parent": "20260720-research-things-to-do-in-or-near-harpenden-london-",
      "list": null,
      "status": "open",
      "description": null
    },
    {
      "id": "20260720-research-car-free-routes-from-harpenden-to-cooling",
      "task": "Research car-free routes from Harpenden to cooling day trips",
      "category": "chore",
      "sat_for_hours": 0,
      "plan": null,
      "from": "sidekick",
      "shared": true,
      "parent": "20260720-research-things-to-do-in-or-near-harpenden-london-",
      "list": null,
      "status": "open",
      "description": null
    },
    {
      "id": "20260720-research-things-to-do-in-or-near-harpenden-london-",
      "task": "Research things to do in or near Harpenden, London if heat strikes while we are there",
      "category": "chore",
      "sat_for_hours": 0,
      "plan": {
        "summary": "Broken into 4 sub-tasks",
        "steps": [
          {
            "text": "Find heat-safe indoor activities near Harpenden for young kids — [[20260720-find-heat-safe-indoor-activities-near-harpenden-fo]]"
          },
          {
            "text": "Research car-free routes from Harpenden to cooling day trips — [[20260720-research-car-free-routes-from-harpenden-to-cooling]]"
          },
          {
            "text": "Identify shaded parks splash pads and pools near Harpenden — [[20260720-identify-shaded-parks-splash-pads-and-pools-near-h]]"
          },
          {
            "text": "Build a hot-weather shortlist with costs hours and backup notes — [[20260720-build-a-hot-weather-shortlist-with-costs-hours-and]]"
          }
        ]
      },
      "from": "dalton",
      "shared": true,
      "parent": null,
      "list": "england-vacation",
      "status": "open",
      "description": "We are two families, with two kids each, kids are 3, 5 and 7. One family does not have a car."
    },
    {
      "id": "20260720-build-a-hot-weather-shortlist-with-costs-hours-and",
      "task": "Build a hot-weather shortlist with costs hours and backup notes",
      "category": "chore",
      "sat_for_hours": null,
      "plan": null,
      "from": "sidekick",
      "shared": true,
      "parent": "20260720-research-things-to-do-in-or-near-harpenden-london-",
      "list": null,
      "status": "done",
      "completed_at": "2026-07-20T20:59:34.582Z",
      "description": null
    }
  ],
  "stats": {
    "total": 1,
    "by_category": {
      "chore": 1
    },
    "median_sat_hours": 0,
    "by_weekday": [
      1,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "by_hour": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      1,
      0,
      0,
      0
    ],
    "streak_days": 1
  },
  "lists": [
    {
      "id": "england-vacation",
      "name": "England - Vacation",
      "created": "2026-07-20T20:37:47Z"
    }
  ]
};
